"""
hf_integration.py — GPT-2 generation with PrismKV compressed KV cache.

Usage:
    python3 examples/hf_integration.py

Expected output:
    A short story generated by GPT-2, followed by a memory report showing
    the compression ratio achieved by PrismKV vs FP16 KV cache.
"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM

from prismkv.cache import PrismKVCache, PrismKVConfig

PROMPT = (
    "Once upon a time in a land far away, there lived a young scientist "
    "who discovered that you could compress the key-value cache of a language model "
    "without losing much quality. She called her invention"
)

def main():
    print("Loading GPT-2 …")
    tokenizer = AutoTokenizer.from_pretrained("gpt2")
    model = AutoModelForCausalLM.from_pretrained("gpt2", dtype=torch.float32)
    model.eval()

    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    input_ids = tokenizer(PROMPT, return_tensors="pt")["input_ids"]

    # --- Standard generation (FP32 DynamicCache) ---
    print("\n── Standard DynamicCache ──")
    with torch.no_grad():
        out_standard = model.generate(
            input_ids,
            max_new_tokens=50,
            do_sample=False,
            use_cache=True,
        )
    print(tokenizer.decode(out_standard[0], skip_special_tokens=True))

    # --- PrismKV generation ---
    print("\n── PrismKV Compressed Cache (4+4+4 bits) ──")
    cache = PrismKVCache(PrismKVConfig(bits_z=4, bits_r=4, bits_theta=4))

    with torch.no_grad():
        out_prismkv = model.generate(
            input_ids,
            past_key_values=cache,
            max_new_tokens=50,
            do_sample=False,
            use_cache=True,
        )
    print(tokenizer.decode(out_prismkv[0], skip_special_tokens=True))

    # --- Memory report ---
    fp = cache.memory_footprint()
    print(f"\n── Memory Report ──")
    print(f"  Compressed codes : {fp['codes_bytes'] / 1024:.1f} KB")
    print(f"  FP16 equivalent  : {fp['fp16_bytes'] / 1024:.1f} KB")
    print(f"  Compression      : {fp['compression']:.1f}× vs FP16")
    print(f"  Layers cached    : {fp['n_layers']}")
    print(f"\n  Config: {cache._default_config}")


if __name__ == "__main__":
    main()
